### ISSUE TITLE
Bioconda

### ISSUE THREAD

**Issue by karel-brinda** [cobilab/jarvis3#2]
It would be absolutely fantastic if Jarvis3 could be provided on Bioconda. It simplify the installation a lot.

Currently, I can find only Jarvis 1.1 there:
```
$ conda search jarvis
Loading channels: done
# Name                       Version           Build  Channel             
jarvis                           1.1      h031d066_4  bioconda            
jarvis                           1.1      h516909a_0  bioconda            
jarvis                           1.1      h779adbc_1  bioconda            
jarvis                           1.1      hec16e2b_2  bioconda            
jarvis                           1.1      hec16e2b_3  bioconda        
```

**Comment by pratas** [comment]
Hi Karel,

We will try to add this feature in the following days.

Cheers

**Comment by pratas** [comment]
Hi Karel,

We submitted JARVIS3 in Bioconda and are now awaiting for the approval.
Soon you will be able to access JARVIS3 through Bioconda.

Cheers
