### ISSUE TITLE
How to estimate necessary comp resources?

### ISSUE THREAD

**Issue by karel-brinda** [cobilab/jarvis3#3]
Hello,

I'm trying to experimentally replace GeCo3 by JARVIS3, but its resources are really difficult to predict for me.

For instance, I've create a simple 2 Mbp FASTA file but when I run JARVIS3 with even basic params (just `-l5`), it's eating a lot of disk space:
```
-rw-r--r--   1 karel  staff   2.0M Oct 22 17:47 A12WS.seq
-rw-r--r--@  1 karel  staff   2.0M Oct 22 17:47 out.co.tmp
-rw-r--r--@  1 karel  staff   116G Oct 22 19:24 out.co.tmp.jc
```

Is there any way how to estimate mem / disk / time reqs?

If yes, would it be possible to document it in the readme?

**Comment by pratas** [comment]
Hi, 

That's odd...
Can you send the file?

Cheers

**Comment by karel-brinda** [comment]
I'll put this into a separate issue

**Comment by pratas** [comment]
This was fixed in the other issue
