### ISSUE TITLE
For a 2MB file, Jarvis3 eats all available disk space (1.3 TB)

### ISSUE THREAD

**Issue by karel-brinda** [cobilab/jarvis3#4]
```
-rw-r--r--@  1 karel  staff   2.0M Oct 22 17:47 out.co.tmp
-rw-r--r--@  1 karel  staff   1.3T Oct 24 10:17 out.co.tmp.jc
```

## Version & platform

* Jarvis 3 version: fc861b8e383afe314a4d6b7c11e3129e58352ace
* Computer: MacBook Pro, Apple M1 Pro, 16 GB RAM, macOS 14.7

## Original file
[A12WS.fa.txt](https://github.com/user-attachments/files/17503782/A12WS.fa.txt)

## Input seq file

[out.co.tmp.txt](https://github.com/user-attachments/files/17503769/out.co.tmp.txt)

Note: I had to rename the files to txt to make them uploadable here

## Output before killing

```
[2024-10-22 17:47:41 L35] echo Running JARVIS3
Running JARVIS3
[2024-10-22 17:47:41 L36] ./JARVIS3 -v -l5 out.co.tmp
Verbose mode ....................... yes
Force mode ......................... no
Data type .......................... DNA
Pseudo-random seed ................. 0
Neural Network hidden size ......... 40
Neural Network learning rate ....... 0.030
Repeat class model 1:
  [+] Maximum number of repeats .... 3
  [+] Context order ................ 13
  [+] Beta ......................... 0.900
  [+] Gamma ........................ 0.720
  [+] Limit ........................ 5
  [+] Using inversions ............. regular and inversions
  [+] Init weight .................. 0.100
  [+] Cache ........................ 1
Target file ........................ out.co.tmp
Compressing ...
Analyzing data and creating models ...
Compressing 2071606 symbols ...
```

**Comment by pratas** [comment]
Hi Karel,

The file contains \n besides ACGT.
When you use ./JARVIS3 binary only ACGT in files is accepted.
Nevertheless, we set a protection that when non ACGT is found, it give the error.

Cheers
